

export const button_vals = [
    {
        text:"AC",
        width:1,
        value:"clear",
        theme:"k-color-brand-red"
    },
    {
        text:"⌫",
        width:1,
        value:"del",
        theme:"k-color-brand-yellow"
    },
    {
        text:"%",
        width:1,
        value:"%",
        theme:"k-color-brand-green"
    },
    {
        text:"÷",
        width:1,
        value:"/",
        theme:"k-color-brand-green"
    },   
    {
        text:"7",
        width:1,
        value:"7"

    },
    {
        text:"8",
        width:1,
        value:"8"
    },   
    {
        text:"9",
        width:1,
        value:"9"
    },   
    {
        text:"×",
        width:1,
        value:"*",
        theme:"k-color-brand-green"
    },   
    {
        text:"4",
        width:1,
        value:"4"
    },   
    {
        text:"5",
        width:1,
        value:"5"
    },   
    {
        text:"6",
        width:1,
        value:"6"
    },   
    {
        text:"−",
        width:1,
        value:"-",
        theme:"k-color-brand-green"
    },   
    {
        text:"1",
        width:1,
        value:"1"
    },   
    {
        text:"2",
        width:1,
        value:"2"
    },   
    {
        text:"3",
        width:1,
        value:"3"
    },
    {
        text:"+",
        width:1,
        value:"+",
        theme:"k-color-brand-green"
    }, 
    {
        text:"⛶",
        width:1,
        value:"full_screen",
        theme:"k-color-brand-green"
    }, 
    {
        text:"0",
        width:1,
        value:"0"
    },
    {
        text:".",
        width:1,
        value:"."
    },
    {
        text:"=",
        width:1,
        value:"=",
        theme:"k-color-brand-yellow"
    },

]

